version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=15d'
      - '--web.enable-remote-write-receiver'
    ports:
      - "9090:9090"
    networks:
      - api-server-network

  loki:
    image: grafana/loki:3.1.0
    container_name: loki
    restart: unless-stopped
    command:
      - '-config.file=/etc/loki/loki-config.yml'
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml:ro
      - loki-data:/loki
    networks:
      - api-server-network


  promtail:
    image: grafana/promtail:3.1.0
    container_name: promtail
    restart: unless-stopped
    command:
      - '-config.file=/etc/promtail/config.yml'
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - api-server-network
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - api-server-network
    depends_on:
      - prometheus
      - loki

volumes:
  prometheus-data:
  grafana-data:
  loki-data:

networks:
  api-server-network:
    external: true
