server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/promtail-positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: api-server
    static_configs:
      - targets:
          - localhost
        labels:
          app: api-server
          job: api-server
          container_name: api-server-green
          __path__: /var/lib/docker/containers/*/*-json.log

    pipeline_stages:
      - docker: {}
